# -*- coding: utf-8 -*-
"""T073 siddhant chalke

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c4Ym_qLv0Qs8DbWHollVbMG06hbBMWNP
"""

dict_hn = {
    'Andheri': 20,
    'Bandra': 10,
    'Kurla': 12,
    'Dadar': 0
}

dict_gn = dict(
    Andheri=dict(Bandra=8, Kurla=12),
    Bandra=dict(Andheri=8, Dadar=7),
    Kurla=dict(Andheri=12, Dadar=8),
    Dadar=dict(Bandra=7, Kurla=8)
)

import queue as Q

start = 'Andheri'
goal = 'Dadar'
result = ''

def DLS(city, visitedstack, startlimit, endlimit):
    global result
    found = 0
    result = result + city + ' '
    visitedstack.append(city)

    if city == goal:
        return 1

    if startlimit == endlimit:
        return 0

    for eachcity in dict_gn[city].keys():
        if eachcity not in visitedstack:
            found = DLS(eachcity, visitedstack, startlimit + 1, endlimit)
            if found:
                return found

def IDDFS(city, visitedstack, endlimit):
    global result

    for i in range(0, endlimit):
        print("Searching at Limit:", i)
        found = DLS(city, visitedstack, 0, i)

        if found:
            print("Found")
            break
        else:
            print("Not Found!")
            print(result)
            print("-----")
            result = ''
            visitedstack = []

def main():
    visitedstack = []
    IDDFS(start, visitedstack, 5)

    print("IDDFS Traversal from", start, "to", goal, "is:")
    print(result)

main()